venus:
 admin_default_password: ${venus_adminpwd}
token:
  signature: ${token_signature}
security:
  key: ${security_key}
spring:
  application:
    name: apigateway
  data:
    mongodb:
      #uri: mongodb://fountain:111111@localhost:27017/fountain?authSource=fountain&maxPoolSize=3&minPoolSize=1&maxIdleTimeMS=30000&connectTimeoutMS=30000&socketTimeoutMS=30000      
      uri: mongodb://${mongo_username}:${mongo_password}@localhost:27017/apigateway?authSource=apigateway
  redis:
    timeout: 10000
    password: ${redis_password}
    nodes: localhost:7001
    redisson:
      #nodes: redis://10.1.0.41:27001,redis://10.1.0.41:27002,redis://10.1.0.41:27003
      nodes: redis://localhost:7001
    sentinel: 
      nodes: 
      #nodes: localhost:27001,localhost:27002,localhost:27003
      master: master1
      subscriptionsPerConnection: 200
      subscriptionConnectionPoolSize: 200
    database: 0
    switchFlag: 1
    jedis:
      pool:
        max-active: 200
        max-wait: 200
        max-idle: 200
        min-idle: 1
        shutdown-timeout: 10000
        timeBetweenEvictionRunsMillis: 10000
server:
  port: 9080